modLoader="javafml"
loaderVersion="[2,)"
license="All Rights Reserved"

[[mods]]
modId="grimms"
version="4"
displayName="Grimm's Mod"
displayURL="https://gsdistance.org"
logoFile="logo.png"
credits="tyuXX"
authors="tyuXX"
description="Grimm's newest and bestest Mod!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.grimms]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.grimms]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.grimms]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration