modLoader="javafml"
loaderVersion="[2,)"
license="GNU Lesser General Public License version 3 (LGPLv3)"

[[mods]]
modId="grimmsmod"
version="1.0.0"
displayName="Grimm's Mod"
displayURL="https://gsdistance.org"
logoFile="logo.png"
credits="Cheesecake"
authors="Tyuxx"
description="Grimm's newest and bestest Mod!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.grimmsmod]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.grimmsmod]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.grimmsmod]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration